
trigger:
  branches:
    include:
      - v3

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1

  - task: DockerInstaller@0
    inputs:
      dockerVersion: 'latest'

  - script: |
      docker-compose up --build -d
    displayName: 'Build and run docker-compose'
